import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms & Conditions — amiugly.lol',
  description: 'Terms and conditions for using amiugly.lol.',
}

export default function TermsPage() {
  return (
    <main className="max-w-3xl mx-auto px-6 py-16">
      <h1 className="text-2xl font-bold mb-2" style={{ color: 'var(--text)' }}>Terms & Conditions</h1>
      <p className="text-xs mb-8" style={{ color: 'var(--muted)' }}>Last updated: March 2026</p>

      <div className="space-y-8 text-sm leading-relaxed" style={{ color: 'var(--text)' }}>
        <section>
          <h2 className="font-semibold text-base mb-2">1. Acceptance of Terms</h2>
          <p>By accessing and using amiugly.lol ("the Service"), you accept and agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use the Service.</p>
        </section>

        <section>
          <h2 className="font-semibold text-base mb-2">2. Nature of the Service</h2>
          <p>amiugly.lol is a satirical entertainment website. UglyNet™ is a fictional AI system. The scores, ratings, and assessments generated by this Service are entirely for entertainment purposes and have no scientific validity. They do not constitute genuine assessments of physical attractiveness, health, or any other personal characteristic. Do not take them seriously. We mean this sincerely.</p>
        </section>

        <section>
          <h2 className="font-semibold text-base mb-2">3. User-Submitted Content</h2>
          <p>By submitting a photo to amiugly.lol, you represent and warrant that:</p>
          <ul className="list-disc ml-5 mt-2 space-y-1">
            <li>The photo is of yourself, or you have explicit permission from the person depicted to submit it.</li>
            <li>You are 18 years of age or older.</li>
            <li>You have the right to submit the photo and grant us the rights described in these Terms.</li>
            <li>The photo does not depict minors.</li>
            <li>The photo does not contain illegal content.</li>
          </ul>
          <p className="mt-3">If you consent to gallery inclusion, you grant amiugly.lol a non-exclusive, royalty-free license to display your photo and results in our public gallery. You may request removal at any time by contacting hello@amiugly.lol.</p>
        </section>

        <section>
          <h2 className="font-semibold text-base mb-2">4. Prohibited Uses</h2>
          <p>You may not use amiugly.lol to:</p>
          <ul className="list-disc ml-5 mt-2 space-y-1">
            <li>Submit photos of other people without their consent.</li>
            <li>Submit photos of minors.</li>
            <li>Harass, bully, or harm others using content generated by the Service.</li>
            <li>Attempt to reverse-engineer, scrape, or otherwise extract data from the Service in unauthorized ways.</li>
            <li>Use the Service in any way that violates applicable laws or regulations.</li>
          </ul>
        </section>

        <section>
          <h2 className="font-semibold text-base mb-2">5. Disclaimer of Warranties</h2>
          <p>The Service is provided "as is" without warranties of any kind, express or implied. amiugly.lol makes no representations that the Service will be uninterrupted, error-free, or that results will be accurate, reliable, or meaningful in any way. The scores are entertainment. We cannot stress this enough.</p>
        </section>

        <section>
          <h2 className="font-semibold text-base mb-2">6. Limitation of Liability</h2>
          <p>To the maximum extent permitted by applicable law, amiugly.lol shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service. This includes, but is not limited to, any emotional distress caused by your score. Again: the score is not real. You look fine.</p>
        </section>

        <section>
          <h2 className="font-semibold text-base mb-2">7. Advertising</h2>
          <p>amiugly.lol displays advertisements through Google AdSense. Google may use cookies to serve ads based on your prior visits to this and other websites. You can opt out of personalized advertising by visiting Google&apos;s Ads Settings.</p>
        </section>

        <section>
          <h2 className="font-semibold text-base mb-2">8. Changes to Terms</h2>
          <p>We reserve the right to modify these Terms at any time. Changes will be posted on this page with an updated date. Continued use of the Service after changes constitutes acceptance of the new Terms.</p>
        </section>

        <section>
          <h2 className="font-semibold text-base mb-2">9. Contact</h2>
          <p>Questions about these Terms? Contact us at <a href="mailto:hello@amiugly.lol" className="hover:opacity-80" style={{ color: 'var(--accent)' }}>hello@amiugly.lol</a>.</p>
        </section>
      </div>
    </main>
  )
}
